# **San Francisco Crime Project**

- **Author:** Muhammad Jawad [@mjawad17]()
- **Description:** Data analysis, exploration, visualization, and data mining on crime in SF
- **Original dataset:** [SF Gov Crime dataset](https://data.sfgov.org/Public-Safety/Police-Department-Incident-Reports-Historical-2003/tmnf-yvry/about_data)
- **Kaggle dataset:** [Kaggle SF Crime](https://www.kaggle.com/competitions/sf-crime/overview)

<div style="border: 2px solid #4CAF50; border-radius: 10px; padding: 20px; background-color: #f9f9f9; font-family: Arial, sans-serif; color: #333;">
    <h2 style="color: #4CAF50;">Author Overview</h2>
    <!-- Round image centered -->
    <img src="https://avatars.githubusercontent.com/u/77524488?s=400&u=5ee60100c5daf1eb876be2bc80aaa0e9e85969c3&v=4" alt="Author Image" style="border-radius: 12%; width: 200px; height: 200px; margin-bottom: 20px; border: 2px solid green; display: block; margin-left: auto; margin-right: auto;">
    <p>I am <strong>Muhammad Jawad</strong>, a passionate data analyst dedicated to leveraging data to drive meaningful insights and support decision-making. With a strong foundation in computer science, I continuously seek to enhance my skills in analytical thinking and data-driven solutions. 📊</p>
    <h3 style="color: #4CAF50;">What Do I Know?</h3>
    <p>I excel at extracting valuable insights from data using Python, SQL, and data visualization tools like Power BI and Tableau. My experience includes analyzing insurance and medical data, as well as performing exploratory data analysis to uncover trends and patterns. I'm committed to improving my statistical analysis and reporting abilities to solve complex problems effectively. 📚</p>
    <h3 style="color: #4CAF50;">What Am I Doing Right Now?</h3>
    <p>Currently, I am focused on expanding my knowledge in data science, particularly in machine learning and advanced analytics. I am eager to apply my theoretical knowledge to real-world projects that challenge me and contribute to organizational success. 🎯</p>
    <h3 style="color: #4CAF50;">My Goal:</h3>
    <p>To utilize my data analysis and data science skills to create value for companies by supporting their growth objectives. I am enthusiastic about learning new concepts and sharing my experiences with others. If you’re interested in discussing projects, collaborating, or exchanging ideas, I would love to connect!</p>
</div>

# Table of Contents
- Introduction
    - SF Crime Dataset
- Basic Preparation
    - Import libraries
    - Load data
- Data Exploration/Analysis Extension
- Data Preprocessing
    - Data Imputation/Removal
    - Feature Engineering
    - Feature Encoding
- Build Machine Learning Models
    - Train different baseline models
    - Analyze results
- Model Selection
- Hyperparameter tuning
- Train Model with optimal hyperparameters
- Feature Selection
    - Feature Importance
    - Feature Removal
- Train Final Model
- Model Evaluation
- Summary
<!-- - Kaggle Submission -->
- Conclusion

# Introduction

## SF Crime Dataset

This dataset includes information about crime incidents reported by the **San Francisco Police Department (SFPD)**. It covers data from _January 1, 2003, to May 13, 2015_.

The dataset is divided into **two groups**: a training set and a test set. These sets rotate weekly. This means that in odd weeks (like the 1st, 3rd, 5th, and 7th weeks), the data is used for the test set. In even weeks (like the 2nd, 4th, 6th, and 8th weeks), the data is used for the training set.

The main **objective** of this dataset is to predict the category of crime that took place in San Francisco based on the available information.

### Data Fields
- **Dates** - timestamp of the crime incident
- **Category** - category of the crime incident (only in train.csv). This is the target variable you are going to predict.
- **Descript** - detailed description of the crime incident (only in train.csv)
- **DayOfWeek** - the day of the week
- **PdDistrict** - name of the Police Department District
- **Resolution** - how the crime incident was resolved (only in train.csv)
- **Address** - the approximate street address of the crime incident
- **X** - Longitude
- **Y** - Latitude

---

In this Jupyter notebook, I will take you through the entire process of creating a machine learning model using the open-source San Francisco Crime dataset. This will be a step-by-step journey that includes several important stages.

First, I will explore and analyze the data to understand its structure and contents. This is a crucial step that helps identify patterns and insights within the data. Next, I will preprocess the data, which is a significant part of this project. This step involves cleaning the data and performing feature engineering to create useful variables for the model.

After preparing the data, I will try out different machine learning algorithms to see which one works best for this dataset. I will determine the most effective model and then fine-tune its hyperparameters to improve its performance. Finally, I will evaluate the chosen model using a metric called multiclass log loss to assess how well it predicts the categories of crime.

Since this project is based on an older Kaggle competition, I will avoid looking for external resources or past Kaggle notebooks. My goal is to enhance my coding skills for an end-to-end data science project and to become more familiar with Python data science libraries. I also hope to uncover interesting insights and discover cool patterns while working with this dataset. So, let’s get started!

# Basic Preparation

## Import Libraries

In [42]:
pip install scikit-optimize

Requirement already satisfied: scikit-optimize in c:\users\786\miniconda3\envs\myenv\lib\site-packages (0.10.2)
Requirement already satisfied: joblib>=0.11 in c:\users\786\miniconda3\envs\myenv\lib\site-packages (from scikit-optimize) (1.5.0)
Requirement already satisfied: pyaml>=16.9 in c:\users\786\miniconda3\envs\myenv\lib\site-packages (from scikit-optimize) (25.5.0)
Requirement already satisfied: numpy>=1.20.3 in c:\users\786\miniconda3\envs\myenv\lib\site-packages (from scikit-optimize) (2.2.5)
Requirement already satisfied: scipy>=1.1.0 in c:\users\786\miniconda3\envs\myenv\lib\site-packages (from scikit-optimize) (1.15.3)
Requirement already satisfied: scikit-learn>=1.0.0 in c:\users\786\miniconda3\envs\myenv\lib\site-packages (from scikit-optimize) (1.6.1)
Requirement already satisfied: packaging>=21.3 in c:\users\786\miniconda3\envs\myenv\lib\site-packages (from scikit-optimize) (24.2)
Requirement already satisfied: PyYAML in c:\users\786\miniconda3\envs\myenv\lib\site-packages (from pyaml>=16.9->scikit-optimize) (6.0.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\786\miniconda3\envs\myenv\lib\site-packages (from scikit-learn>=1.0.0->scikit-optimize) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [43]:
__author__ = "Muhammad Jawad (https://github.com/mj-awad17)"

# linear algebra
import numpy as np

# data manipulation
import pandas as pd

# plotting
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import style
%matplotlib inline
style.use('ggplot')

# preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

# machince learning algorithms
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression, SGDClassifier, Perceptron
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
import xgboost as xgb

# model evaluation metrics
from sklearn.metrics import log_loss
from sklearn.model_selection import cross_val_score

# model selection and tuning
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, StratifiedGroupKFold
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer

# clustering
from sklearn.cluster import KMeans

# mathematical fundtions
import math

# ignore warnings
import warnings
warnings.filterwarnings("ignore")

## Load Data

In [44]:
train = pd.read_csv('../../All/train.csv')
test = pd.read_csv('../../All/test.csv')

In [45]:
# info of train data
print("Train Data Info:")
print(train.info())

Train Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878049 entries, 0 to 878048
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Dates       878049 non-null  object
 1   Category    878049 non-null  object
 2   Descript    878049 non-null  object
 3   DayOfWeek   878049 non-null  object
 4   PdDistrict  878049 non-null  object
 5   Resolution  878049 non-null  object
 6   Address     878049 non-null  object
 7   X           878049 non-null  float64
 8   Y           878049 non-null  float64
dtypes: float64(2), object(7)
memory usage: 60.3+ MB
None

# Data Exploration & Analysis Extension

- Complete data exploration & visualizations are done in jupyter notebook: [sf-crime-data-exploration.ipynb](sf-crime-exploration.ipynb)
- This dataset suffers from **imbalanced** classes (TREA has 6 occurrences while LARCENY/THEFT has 1,749,000 occurrences)
    - There are a couple ways to deal with **imbalanced** classes, such as:
        - Changing performance metric (Do not use accuracy, use a confusion matrix, precision, recall, F1 score, ROC curves)
        - Resample dataset (Oversample under-represented classes, and undersample over-represented classes)
        - Try different ML algorithms that can handle imbalanced classes
            - Decision Trees (Random Forests/XGBoost) often perform well on imbalanced classes (due to splitting rules)

In [46]:
train.head()

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y
0,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
1,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
2,2015-05-13 23:33:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",VANNESS AV / GREENWICH ST,-122.424363,37.800414
3,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,NORTHERN,NONE,1500 Block of LOMBARD ST,-122.426995,37.800873
4,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,PARK,NONE,100 Block of BRODERICK ST,-122.438738,37.771541

In [47]:
train.columns.values

array(['Dates', 'Category', 'Descript', 'DayOfWeek', 'PdDistrict',
       'Resolution', 'Address', 'X', 'Y'], dtype=object)

### Things we Observed so far:
- 878,049 instances in training set (or recorded crime instances in SF)
- 9 columns (8 potential features + 1 label (Category))

**Data types:**

- 2 columns with float values
- 7 objects

There are no null (NaN) values (Yaha!)

In [48]:
# Count number of observations for each crime 
train['Category'].value_counts()

Category
LARCENY/THEFT                  174900
OTHER OFFENSES                 126182
NON-CRIMINAL                    92304
ASSAULT                         76876
DRUG/NARCOTIC                   53971
VEHICLE THEFT                   53781
VANDALISM                       44725
WARRANTS                        42214
BURGLARY                        36755
SUSPICIOUS OCC                  31414
MISSING PERSON                  25989
ROBBERY                         23000
FRAUD                           16679
FORGERY/COUNTERFEITING          10609
SECONDARY CODES                  9985
WEAPON LAWS                      8555
PROSTITUTION                     7484
TRESPASS                         7326
STOLEN PROPERTY                  4540
SEX OFFENSES FORCIBLE            4388
DISORDERLY CONDUCT               4320
DRUNKENNESS                      4280
RECOVERED VEHICLE                3138
KIDNAPPING                       2341
DRIVING UNDER THE INFLUENCE      2268
RUNAWAY                          1946
LIQUOR LAWS                      1903
ARSON                            1513
LOITERING                        1225
EMBEZZLEMENT                     1166
SUICIDE                           508
FAMILY OFFENSES                   491
BAD CHECKS                        406
BRIBERY                           289
EXTORTION                         256
SEX OFFENSES NON FORCIBLE         148
GAMBLING                          146
PORNOGRAPHY/OBSCENE MAT            22
TREA                                6
Name: count, dtype: int64

In [49]:
# Count number of observations for each PdDistrict
train['PdDistrict'].value_counts()

PdDistrict
SOUTHERN      157182
MISSION       119908
NORTHERN      105296
BAYVIEW        89431
CENTRAL        85460
TENDERLOIN     81809
INGLESIDE      78845
TARAVAL        65596
PARK           49313
RICHMOND       45209
Name: count, dtype: int64

In [50]:
# Count number of observations for each DayOfWeek
train['DayOfWeek'].value_counts()

DayOfWeek
Friday       133734
Wednesday    129211
Saturday     126810
Thursday     125038
Tuesday      124965
Monday       121584
Sunday       116707
Name: count, dtype: int64

In [51]:
# Count number of observations for each DayOfWeek
train['DayOfWeek'].value_counts()

DayOfWeek
Friday       133734
Wednesday    129211
Saturday     126810
Thursday     125038
Tuesday      124965
Monday       121584
Sunday       116707
Name: count, dtype: int64

In [52]:
# Count number of observations for each Resolution
train['Resolution'].value_counts()

Resolution
NONE                                      526790
ARREST, BOOKED                            206403
ARREST, CITED                              77004
LOCATED                                    17101
PSYCHOPATHIC CASE                          14534
UNFOUNDED                                   9585
JUVENILE BOOKED                             5564
COMPLAINANT REFUSES TO PROSECUTE            3976
DISTRICT ATTORNEY REFUSES TO PROSECUTE      3934
NOT PROSECUTED                              3714
JUVENILE CITED                              3332
PROSECUTED BY OUTSIDE AGENCY                2504
EXCEPTIONAL CLEARANCE                       1530
JUVENILE ADMONISHED                         1455
JUVENILE DIVERTED                            355
CLEARED-CONTACT JUVENILE FOR MORE INFO       217
PROSECUTED FOR LESSER OFFENSE                 51
Name: count, dtype: int64

In [53]:
# describe the train data
train.describe().T

,count,mean,std,min,25%,50%,75%,max
X,878049.0,-122.422616,0.030354,-122.513642,-122.432952,-122.416420,-122.406959,-120.5
Y,878049.0,37.771020,0.456893,37.707879,37.752427,37.775421,37.784369,90.0

> There seems to be an invalid coordinates (max) 90 (latitude) or -120.5 (longitude) does not seem to be a valid coordinate in San Francisco. We must fix these values for this feature.

# Data Preprocessing

- Data cleaning
    - imputation or removal of outlier values
- Feature Engineering (Feature Creation)
- Feature Encoding
    - Integer encode or label encode ordinal categorical features that maintain order (Year, Business Quarter, Block/Street Number)
    - Usually:
        - One hot encode nominal categorical features (DayOfWeek, PdDistrict, StreetType, Category) 
            - mainly for logistic regression
        - However, Random Forests & Boosting algorithms can handle nominal categorical features directly, so we just integer encode these features.

## Data Cleaning

In [54]:
train[train['Y'] == train['Y'].max()]

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y
660485,2005-12-30 17:00:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Friday,TENDERLOIN,NONE,5THSTNORTH ST / OFARRELL ST,-120.5,90.0
660711,2005-12-30 00:34:00,ASSAULT,INFLICT INJURY ON COHABITEE,Friday,BAYVIEW,"ARREST, BOOKED",JAMESLICKFREEWAY HY / SILVER AV,-120.5,90.0
660712,2005-12-30 00:34:00,ASSAULT,AGGRAVATED ASSAULT WITH BODILY FORCE,Friday,BAYVIEW,"ARREST, BOOKED",JAMESLICKFREEWAY HY / SILVER AV,-120.5,90.0
661106,2005-12-29 00:07:00,NON-CRIMINAL,"AIDED CASE, MENTAL DISTURBED",Thursday,TENDERLOIN,PSYCHOPATHIC CASE,5THSTNORTH ST / EDDY ST,-120.5,90.0
666430,2005-11-30 11:25:00,OTHER OFFENSES,TRAFFIC VIOLATION,Wednesday,TENDERLOIN,"ARREST, CITED",5THSTNORTH ST / ELLIS ST,-120.5,90.0
...,...,...,...,...,...,...,...,...,...
844995,2003-06-11 08:49:00,OTHER OFFENSES,"DRIVERS LICENSE, SUSPENDED OR REVOKED",Wednesday,INGLESIDE,"ARREST, CITED",JAMES LICK FREEWAY HY / CESAR CHAVEZ ST,-120.5,90.0
845842,2003-06-09 09:25:00,OTHER OFFENSES,"DRIVERS LICENSE, SUSPENDED OR REVOKED",Monday,INGLESIDE,"ARREST, CITED",JAMES LICK FREEWAY HY / CESAR CHAVEZ ST,-120.5,90.0
852880,2003-05-02 01:00:00,SEX OFFENSES FORCIBLE,"FORCIBLE RAPE, BODILY FORCE",Friday,SOUTHERN,COMPLAINANT REFUSES TO PROSECUTE,3RD ST / JAMES LICK FREEWAY HY,-120.5,90.0
857248,2003-04-14 16:30:00,ROBBERY,"ROBBERY ON THE STREET, STRONGARM",Monday,BAYVIEW,COMPLAINANT REFUSES TO PROSECUTE,GILMAN AV / FITCH ST,-120.5,90.0
871198,2003-02-05 12:00:00,LARCENY/THEFT,PETTY THEFT FROM LOCKED AUTO,Wednesday,SOUTHERN,NONE,SPEAR ST / THE EMBARCADERO SOUTH ST,-120.5,90.0

I notice that there are `108` **rows** with incorrect coordinates, and they seem to be the exact same two coordinates (90, -120.5). There are many ways to handle this. We need to do data **imputation**, which can be done several ways. For now, I will randomly sample from a normal distribution with the range of a standard deviation from the mean. However, I could use a linear regression model to predict the latitude and longitude values (based on other variables such as PD district?) and use that to impute the bad / inconsistent data points.

Another method is to completely remove this data. Since I already have a lot of data, and I do not want this incorrect data to affect my results, I could remove them. However, I will stick with data imputation.

In [55]:
# replace the max value of Y and X with NaN: both Train and test data
train['Y'].replace(to_replace= train['Y'].max() ,value=np.nan, inplace=True)
train['X'].replace(to_replace= train['X'].max() ,value=np.nan, inplace=True)
test['Y'].replace(to_replace= test['Y'].max() ,value=np.nan, inplace=True)
test['X'].replace(to_replace= test['X'].max() ,value=np.nan, inplace=True)

In [56]:
print("Train Dataset:", train.isnull().sum())
print("\nTest Dataset:", test.isnull().sum())

Train Dataset: Dates          0
Category       0
Descript       0
DayOfWeek      0
PdDistrict     0
Resolution     0
Address        0
X             67
Y             67
dtype: int64

Test Dataset: Id             0
Dates          0
DayOfWeek      0
PdDistrict     0
Address        0
X             76
Y             76
dtype: int64

In [57]:
# combine train and test data for preprocessing
df = [train, test]

# iterate through the dataframes for statistical methods used
for data in df:
    mean_X = data['X'].mean()
    std_X = data['X'].std()
    mean_Y = data['Y'].mean()
    std_Y = data['Y'].std()
    max_x = mean_X + std_X
    min_x = mean_X - std_X
    max_y = mean_Y + std_Y
    min_y = mean_Y - std_Y

    # both X and Y are same so just using Y
    is_null = data['Y'].isnull().sum()

    random_X = (max_x - min_x) * np.random.randn(is_null) + min_x
    random_Y = (max_y - min_y) * np.random.randn(is_null) + min_y

    X_slice = data['X'].copy()
    Y_slice = data['Y'].copy()
    X_slice[np.isnan(X_slice)] = random_X
    Y_slice[np.isnan(Y_slice)] = random_Y
    data['X'] = X_slice
    data['Y'] = Y_slice

In [58]:
train[['X', 'Y']].describe().T

,count,mean,std,min,25%,50%,75%,max
X,878049.0,-122.422764,0.025287,-122.535985,-122.432952,-122.416421,-122.406959,-122.355798
Y,878049.0,37.767033,0.024168,37.619727,37.752427,37.775421,37.784368,37.853885

In [59]:
len(test)

884262

## Feature Engineering
- Let's create some new features from the data that exists in the current feature space
- There are a couple categories of features:
    - Temporal features
    - Spatial features

### Temporal Features
We want to have a column for Time, so we must parse through the 'Dates' feature to create the 'Time' feature

In [60]:
# Transform the Date into a python datetime object.
train["Dates"] = pd.to_datetime(train["Dates"], format="%Y-%m-%d %H:%M:%S")
test["Dates"] = pd.to_datetime(test["Dates"], format="%Y-%m-%d %H:%M:%S")

In [61]:
# minutes
train["Minutes"] = train["Dates"].map(lambda x: x.minute)
test["Minutes"] = test["Dates"].map(lambda x: x.minute)
# hours
train["Hours"] = train["Dates"].map(lambda x: x.hour)
test["Hours"] = test["Dates"].map(lambda x: x.hour)
# days
train["Days"] = train["Dates"].map(lambda x: x.day)
test["Days"] = test["Dates"].map(lambda x: x.day)
# years
train["Years"] = train["Dates"].map(lambda x: x.year)
test["Years"] = test["Dates"].map(lambda x: x.year)

In [62]:
# Hour Zone 0 - Pass midnight, 1 - morning, 2 - afternoon, 3 - dinner / sun set, 4 - night
def hour_zone(hour):
    if hour < 1:
        return 0
    elif hour < 6:
        return 1
    elif hour < 12:
        return 2
    elif hour < 18:
        return 3
    else:
        return 4

train["HourZone"] = train["Hours"].map(hour_zone)
test["HourZone"] = test["Hours"].map(hour_zone)

In [63]:
# Add Week of Year
train["WeekOfYear"] = train["Dates"].map(lambda x: int(x.weekofyear / 2) - 1)
test["WeekOfYear"] = test["Dates"].map(lambda x: int(x.weekofyear / 2))

print(sorted(train['WeekOfYear'].unique()))
print(sorted(test['WeekOfYear'].unique()))

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25)]
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26)]

In [64]:
train.head()

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y,Minutes,Hours,Days,Years,HourZone,WeekOfYear
0,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599,53,23,13,2015,4,9
1,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599,53,23,13,2015,4,9
2,2015-05-13 23:33:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",VANNESS AV / GREENWICH ST,-122.424363,37.800414,33,23,13,2015,4,9
3,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,NORTHERN,NONE,1500 Block of LOMBARD ST,-122.426995,37.800873,30,23,13,2015,4,9
4,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,PARK,NONE,100 Block of BRODERICK ST,-122.438738,37.771541,30,23,13,2015,4,9

### Holiday Feature
- Certain crimes may be more apparent on holidays

In [65]:
from pandas.tseries.holiday import USFederalHolidayCalendar as calendar

# Training set
cal = calendar()
holidays = cal.holidays(start=train['Dates'].min(), end=train['Dates'].max())
train['Holiday'] = train['Dates'].dt.date.astype('datetime64[ns]').isin(holidays)

In [66]:
print("Train:", len(train[train['Holiday'] == True]))
# print("Test:", len(test[test['Holiday'] == True]))

Train: 25653

### Business Hours Feature
- There should be an effect of business hours on the type of crime committed
- Let's create a binary feature where:
    - 1 is typical business hours [8:00AM - 6:00PM]
    - 0 is not business hours [6:01PM - 7:59 AM]

In [67]:
from datetime import datetime, time

def time_in_range(start, end, x):
    """Return true if x is in the inclusive range [start, end]"""
    if start <= end:
        return start <= x <= end
    else:
        return start <= x or x <= end

def map_business_hours(date):
    
    # Convert military time to AM & PM
    time_parsed = date.time()
    business_start = time(8, 0, 0)
    business_end = time(18, 0, 0)
    
    if time_in_range(business_start, business_end, time_parsed):
        return 1
    else:
        return 0
    
train['BusinessHour'] = train['Dates'].map(map_business_hours).astype('uint8')
test['BusinessHour'] = test['Dates'].map(map_business_hours).astype('uint8')

In [68]:
train['BusinessHour'].value_counts()

BusinessHour
1    455215
0    422834
Name: count, dtype: int64

In [69]:
train.sample(5)

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y,Minutes,Hours,Days,Years,HourZone,WeekOfYear,Holiday,BusinessHour
150690,2013-05-16 14:00:00,VANDALISM,"MALICIOUS MISCHIEF, VANDALISM OF VEHICLES",Thursday,NORTHERN,NONE,FELL ST / VANNESS AV,-122.419508,37.776370,0,14,16,2013,3,9,False,1
361019,2010-05-07 12:00:00,SUSPICIOUS OCC,SUSPICIOUS OCCURRENCE,Friday,RICHMOND,NONE,500 Block of 7TH AV,-122.465069,37.778099,0,12,7,2010,3,8,False,1
483028,2008-07-24 21:29:00,NON-CRIMINAL,"AIDED CASE, MENTAL DISTURBED",Thursday,SOUTHERN,NONE,500 Block of MINNA ST,-122.408771,37.780136,29,21,24,2008,4,14,False,0
229009,2012-04-19 20:00:00,BURGLARY,"BURGLARY OF APARTMENT HOUSE, UNLAWFUL ENTRY",Thursday,RICHMOND,NONE,6300 Block of GEARY BL,-122.487429,37.780089,0,20,19,2012,4,7,False,0
862758,2003-03-18 11:00:00,VEHICLE THEFT,"VEHICLE, RECOVERED, OTHER VEHICLE",Tuesday,MISSION,NONE,3200 Block of 16TH ST,-122.425495,37.764644,0,11,18,2003,2,5,False,1

### Business Quarter (Removed)
- Business Quarter might have an effect on what types of crimes are commited
- Q1 = 1 (Jan. - March) Q2 = 2 (April - June), Q3 = 3 (July - Sept.), Q4 = 4 (Oct. - Dec.)

In [70]:
# def map_business_quarter(month):
    
#     if month in [1, 2, 3]:
# #         print(time_parsed)
#         return 1
#     elif month in [4, 5, 6]:
#         return 2
#     elif month in [7, 8, 9]:
#         return 3
#     elif month in [10, 11, 12]:
#         return 4
    
# train['Quarter'] = train['Month'].map(map_business_quarter)
# test['Quarter'] = test['Month'].map(map_business_quarter)
# train['Quarter'].value_counts()
# train.head(10)

### Season
The season feature may affect what type of crimes are commited.

- 1 = Winter, 2 = Spring, 3 = Summer, 4 = Fall

In [71]:
train['Season']=(train['Years']%12 + 3)//3
test['Season']=(test['Years']%12 + 3)//3

In [72]:
train.sample(5)

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y,Minutes,Hours,Days,Years,HourZone,WeekOfYear,Holiday,BusinessHour,Season
438361,2009-03-16 12:30:00,FORGERY/COUNTERFEITING,"CHECKS, MAKE OR PASS FICTITIOUS",Monday,INGLESIDE,NONE,400 Block of CORTLAND AV,-122.416821,37.739146,30,12,16,2009,3,5,False,1,2
646124,2006-03-12 03:30:00,BURGLARY,"BURGLARY OF APARTMENT HOUSE, UNLAWFUL ENTRY",Sunday,NORTHERN,NONE,500 Block of HAIGHT ST,-122.431290,37.772055,30,3,12,2006,1,4,False,0,1
435914,2009-03-22 02:07:00,OTHER OFFENSES,RESISTING ARREST,Sunday,CENTRAL,"ARREST, BOOKED",POWELL ST / UNION ST,-122.410836,37.800239,7,2,22,2009,1,5,False,0,2
172533,2013-01-27 07:20:00,NON-CRIMINAL,"CIVIL SIDEWALKS, CITATION",Sunday,PARK,"ARREST, CITED",STANYAN ST / HAIGHT ST,-122.453535,37.769166,20,7,27,2013,2,1,False,0,4
640459,2006-04-09 17:00:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Sunday,TENDERLOIN,NONE,100 Block of OFARRELL ST,-122.407244,37.786565,0,17,9,2006,3,6,False,1,1

### Weekend
Weekends may have effect on what types of crimes are commmited
- Weekday = 0, Weekend =1

In [73]:
# Weekend Feature

# Weekday = 0, Weekend = 1
days = {'Monday':0 ,'Tuesday':0 ,'Wednesday':0 ,'Thursday':0 ,'Friday':0, 'Saturday':1 ,'Sunday':1}

train['Weekend'] = train['DayOfWeek'].replace(days).astype('uint8')
test['Weekend'] = test['DayOfWeek'].replace(days).astype('uint8')

## Spatial Features
### Street Type
The street type can have an effect on what type of crime is committed, so we want to extract the street type from the 'Address' feature.

We have avenues, streets, ways, boulevards, highways, courts, walks, plazas, and differet number of intersections of roads/streets (Addresses with /).

In [74]:
train['Address'].value_counts().index

Index(['800 Block of BRYANT ST', '800 Block of MARKET ST',
       '2000 Block of MISSION ST', '1000 Block of POTRERO AV',
       '900 Block of MARKET ST', '0 Block of TURK ST', '0 Block of 6TH ST',
       '300 Block of ELLIS ST', '400 Block of ELLIS ST',
       '16TH ST / MISSION ST',
       ...
       'KENWOOD WY / UPLAND DR', 'AVALON AV / PERU AV',
       'OFARRELL ST / ANZA VISTA AV', '400 Block of POINT LOBOS AV',
       'KNOLLVIEW WY / CITYVIEW WY', 'VAN DYKE AV / LANE ST',
       'VAN NESS AV / IVY ST', 'STANYAN ST / BELGRAVE AV',
       '0 Block of NORIEGA ST', '200 Block of JESSIE ST'],
      dtype='object', name='Address', length=23228)

In [75]:
import re

    
def find_streets(address):
    street_types = ['AV', 'ST', 'CT', 'PZ', 'LN', 'DR', 'PL', 'HY', 
                    'FY', 'WY', 'TR', 'RD', 'BL', 'WAY', 'CR', 'AL', 'I-80',  
                    'RW', 'WK','EL CAMINO DEL MAR']
    street_pattern = '|'.join(street_types)
    streets = re.findall(street_pattern, address)
    if len(streets) == 0:
        # Debug
#         print(address)
        return 'OTHER'
    elif len(streets) == 1:
        return streets[0]
    else:
#         print(address)
        return 'INT'

train['StreetType'] = train['Address'].map(find_streets)
test['StreetType'] = test['Address'].map(find_streets)

In [76]:
train['StreetType'].value_counts()

StreetType
INT                  389995
ST                   358797
AV                    92467
BL                    13074
DR                     8200
WY                     4063
RD                     2384
PZ                     2347
CT                     2059
LN                     1356
PL                      863
HY                      819
TR                      766
I-80                    322
CR                      291
AL                      150
WAY                      55
EL CAMINO DEL MAR        21
OTHER                    14
WK                        5
RW                        1
Name: count, dtype: int64

In [77]:
train['StreetType'].isnull().sum()

np.int64(0)

In [78]:
train.head(8)

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y,Minutes,Hours,Days,Years,HourZone,WeekOfYear,Holiday,BusinessHour,Season,Weekend,StreetType
0,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599,53,23,13,2015,4,9,False,0,4,0,INT
1,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599,53,23,13,2015,4,9,False,0,4,0,INT
2,2015-05-13 23:33:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",VANNESS AV / GREENWICH ST,-122.424363,37.800414,33,23,13,2015,4,9,False,0,4,0,INT
3,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,NORTHERN,NONE,1500 Block of LOMBARD ST,-122.426995,37.800873,30,23,13,2015,4,9,False,0,4,0,INT
4,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,PARK,NONE,100 Block of BRODERICK ST,-122.438738,37.771541,30,23,13,2015,4,9,False,0,4,0,ST
5,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM UNLOCKED AUTO,Wednesday,INGLESIDE,NONE,0 Block of TEDDY AV,-122.403252,37.713431,30,23,13,2015,4,9,False,0,4,0,AV
6,2015-05-13 23:30:00,VEHICLE THEFT,STOLEN AUTOMOBILE,Wednesday,INGLESIDE,NONE,AVALON AV / PERU AV,-122.423327,37.725138,30,23,13,2015,4,9,False,0,4,0,INT
7,2015-05-13 23:30:00,VEHICLE THEFT,STOLEN AUTOMOBILE,Wednesday,BAYVIEW,NONE,KIRKWOOD AV / DONAHUE ST,-122.371274,37.727564,30,23,13,2015,4,9,False,0,4,0,INT

### Block Features (Removed)
- Let's explore and create the block feature, since we saw it a lot in the address features
- Binary feature
    - Categorize address that contains 'Block', as having a block, and if no block exists, we will assign to 0.
- 617231 addresses with blocks
- 260818 addresses with no blocks

In [79]:
def find_block(address):
    block_pattern = 'Block'
    blocks = re.search(block_pattern, address)
    if blocks:
#         print(address)
        return 1
    else:
#         print(address)
        return 0

In [80]:
train['Block'] = train['Address'].map(find_block)
test['Block'] = test['Address'].map(find_block)
train['Block'].value_counts()

Block
1    617231
0    260818
Name: count, dtype: int64

### Block Number Feature
- Let's explore the block number from address
- Block number has ordinal data type (order matters), and has spatial significance
- It seems all the block numbers are in intervals of 100
- How to categorize
    - Addresses that do not have a block number will be categorized as 0
    - Addresses with block number will be divided by 100, and added by 1 for mapping (0 is saved for addresses with no block number)
- 85 unique block numbers (including 1 where there is no block number)

In [82]:
def find_block_number(address):
    block_num_pattern = '[0-9]+\s[Block]'
    block_num = re.search(block_num_pattern, address)
    if block_num:
#         print(address)
        num_pattern = '[0-9]+'
        block_no_pos = re.search(num_pattern, address)
        # Get integer of found regular expression
        block_no = int(block_no_pos.group())
        # Convert block number by dividing by 100 and adding 1 (0 = addresses with no block)
        block_map = (block_no // 100) + 1
#         print(block_map)
        return block_map
    else:
#         print(address)
        # 
        return 0


train['BlockNo'] = train['Address'].map(find_block_number)
test['BlockNo'] = test['Address'].map(find_block_number)

In [83]:
train['BlockNo'].value_counts()

BlockNo
0     260818
1      76325
2      51917
9      51718
3      38407
       ...
82         7
79         5
81         4
84         4
80         3
Name: count, Length: 85, dtype: int64

## X, Y Coordinates
- Normalize and scale the X and Y coordinates
- I use K-Means clustering to create a new feature for the longitude and latitude by grouping clusters of points based on Euclidean distances.
- X = longitude, Y = latitude
- I also extract more spatial features from the X, Y coordinates by transforming them from the cartesian space to the polar space (Reference)
    1. three variants of rotated Cartesian coordinates (rotated by 30, 45, 60 degree each)
    2. Polar coordinates (i.e. the 'r' and the angle 'theta')
    3. The approach makes some intuitive sense i.e. that having such features should help in extracting some more spatial information (than relying on the current x-y alone)

In [84]:
# Normalize X and Y
print('There are %d unique longitude values, %d unique latitude values' % (train['X'].nunique(), 
                                                                           train['Y'].nunique()))

xy_scaler = StandardScaler().fit(train[['X', 'Y']])
train[['X', 'Y']] = xy_scaler.transform(train[['X', 'Y']])
test[['X', 'Y']] = xy_scaler.transform(test[['X', 'Y']])

There are 34309 unique longitude values, 34309 unique latitude values

In [86]:
# X-Y plane rotation and space transformation to extract more spatial information
# 2-dimensional rotation based on below functions:
# rotated x = xcos - ysin
# rotated y = xsin + ycos
# Conver from cartesian space -> polar space

cos_30 = math.cos(math.radians(30))
sin_30 = math.sin(math.radians(30))
cos_45 = math.cos(math.radians(45))
sin_45 = math.sin(math.radians(45))
cos_60 = math.cos(math.radians(60))
sin_60 = math.sin(math.radians(60))


train["Rot30_X"] = train['X'] * cos_30 - train['Y'] * sin_30 
train["Rot30_Y"] = train['X'] * sin_30 + train['Y'] * cos_30
train["Rot45_X"] = train['X'] * cos_45 - train['Y'] * sin_45  
train["Rot45_Y"] = train['X'] * sin_45 + train['Y'] * cos_45
train["Rot60_X"] = train['X'] * cos_60 - train['Y'] * sin_60  
train["Rot60_Y"] = train['X'] * sin_60 + train['Y'] * cos_60
train["Radius"] = np.sqrt(train['X'] ** 2 + train['Y'] ** 2)
train["Angle"] = np.arctan2(train['X'], train['Y'])

test["Rot30_X"] = test['X'] * cos_30 - test['Y'] * sin_30  
test["Rot30_Y"] = test['X'] * sin_30 + test['Y'] * cos_30
test["Rot45_X"] = test['X'] * cos_45 - test['Y'] * sin_45  
test["Rot45_Y"] = test['X'] * sin_45 + test['Y'] * cos_45
test["Rot60_X"] = test['X'] * cos_60 - test['Y'] * sin_60  
test["Rot60_Y"] = test['X'] * sin_60 + test['Y'] * cos_60
test["Radius"] = np.sqrt(test['X'] ** 2 + test['Y'] ** 2)
test["Angle"] = np.arctan2(test['X'], test['Y'])

In [87]:
train.describe()

,Dates,X,Y,Minutes,Hours,Days,Years,HourZone,WeekOfYear,BusinessHour,...,Block,BlockNo,Rot30_X,Rot30_Y,Rot45_X,Rot45_Y,Rot60_X,Rot60_Y,Radius,Angle
count,878049,8.780490e+05,8.780490e+05,878049.000000,878049.000000,878049.000000,878049.000000,878049.000000,878049.000000,878049.000000,...,878049.000000,878049.000000,8.780490e+05,8.780490e+05,8.780490e+05,8.780490e+05,8.780490e+05,8.780490e+05,878049.000000,878049.000000
mean,2009-03-16 08:25:41.991847168,9.255299e-13,1.905462e-14,20.155026,13.412655,15.570623,2008.712046,2.777642,12.185458,0.518439,...,0.702957,7.743576,7.920064e-13,4.792662e-13,6.409820e-13,6.679221e-13,4.462655e-13,8.110573e-13,1.219278,0.278882
min,2003-01-06 00:01:00,-4.477442e+00,-6.095077e+00,0.000000,0.000000,1.000000,2003.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-4.846514e+00,-5.759599e+00,-4.904422e+00,-5.949526e+00,-4.628102e+00,-5.734004e+00,0.020048,-3.141518
25%,2006-01-11 03:00:00,-4.028694e-01,-6.043217e-01,0.000000,9.000000,8.000000,2006.000000,2.000000,6.000000,0.000000,...,0.000000,0.000000,-4.146074e-01,-5.664118e-01,-4.910942e-01,-5.402191e-01,-5.844500e-01,-4.589096e-01,0.742429,-1.065812
50%,2009-03-07 16:00:00,2.508660e-01,3.470730e-01,19.000000,14.000000,16.000000,2009.000000,3.000000,12.000000,1.000000,...,1.000000,4.000000,6.284243e-02,2.143244e-01,-9.704331e-02,2.239787e-01,-2.373206e-01,3.123547e-01,1.003702,0.508756
75%,2012-06-11 10:13:00,6.250528e-01,7.172727e-01,33.000000,19.000000,23.000000,2012.000000,4.000000,19.000000,1.000000,...,1.000000,11.000000,4.804400e-01,8.071559e-01,4.085288e-01,7.867751e-01,5.062806e-01,7.512117e-01,1.639711,1.172382
max,2015-05-13 23:53:00,2.648280e+00,3.593671e+00,59.000000,23.000000,31.000000,2015.000000,4.000000,25.000000,1.000000,...,1.000000,84.000000,5.097068e+00,2.855910e+00,5.837492e+00,2.904920e+00,6.180100e+00,2.873614e+00,6.201117,3.141206
std,NaN,1.000001e+00,1.000001e+00,18.594915,6.549573,8.783005,3.631194,1.142067,7.482940,0.499660,...,0.456956,10.233725,9.308607e-01,1.064660e+00,9.197006e-01,1.074315e+00,9.308607e-01,1.064660e+00,0.716493,1.652413

In [88]:
# run KMeans separately on both the training set and test set
data = [train, test]
num_clusters = 40
for dataset in data:
    coordinates = dataset.loc[:,['Y','X']]
    kmeans = KMeans(n_clusters=num_clusters, n_jobs=3, random_state=1).fit(coordinates)
    id_labels=kmeans.labels_
#     print(kmeans.cluster_centers_)
    dataset['Cluster'] = id_labels

TypeError: KMeans.__init__() got an unexpected keyword argument 'n_jobs'

# Drop Features
- We have already extracted all the necessary features from the Address attribute, so drop
- We don't need Resolution or Descript features since it is not included in the training data

In [89]:
# Drop Address feature from both train and test set
train.drop(['Address'], axis=1, inplace=True)
test.drop(['Address'], axis=1, inplace=True)

In [90]:
# We don't need Dates column anymore
train.drop(['Dates'], axis=1, inplace=True)
test.drop(['Dates'], axis=1, inplace=True)

In [91]:
# Drop Resolution column since test set does not have this column
train.drop(['Resolution'], axis=1, inplace=True)

In [92]:
# Drop Descript column since test set does not have this column
train.drop(['Descript'], axis=1, inplace=True)

In [93]:
# Let's quickly view the data
train.head()

,Category,DayOfWeek,PdDistrict,X,Y,Minutes,Hours,Days,Years,HourZone,...,Block,BlockNo,Rot30_X,Rot30_Y,Rot45_X,Rot45_Y,Rot60_X,Rot60_Y,Radius,Angle
0,WARRANTS,Wednesday,NORTHERN,-0.123676,0.313057,53,23,13,2015,4,...,0,0,-0.263635,0.209277,-0.308817,0.133912,-0.332953,0.049421,0.336601,-0.376241
1,OTHER OFFENSES,Wednesday,NORTHERN,-0.123676,0.313057,53,23,13,2015,4,...,0,0,-0.263635,0.209277,-0.308817,0.133912,-0.332953,0.049421,0.336601,-0.376241
2,OTHER OFFENSES,Wednesday,NORTHERN,-0.063224,1.381234,33,23,13,2015,4,...,0,0,-0.745370,1.164571,-1.021386,0.931974,-1.227795,0.635863,1.382680,-0.045742
3,LARCENY/THEFT,Wednesday,NORTHERN,-0.167322,1.400197,30,23,13,2015,4,...,1,16,-0.845003,1.128945,-1.108403,0.871775,-1.296267,0.555194,1.410159,-0.118935
4,LARCENY/THEFT,Wednesday,PARK,-0.631685,0.186550,30,23,13,2015,4,...,1,2,-0.640330,-0.154286,-0.578579,-0.314758,-0.477399,-0.453781,0.658655,-1.283638

# Feature Encoding
- Convert categorical data to numeric data
## Pd Districts
- convert Pd District categorical feature to numeric

In [94]:
pd_districts = {'SOUTHERN':0, 'MISSION':1, 'NORTHERN':2, 'CENTRAL':3, 'BAYVIEW':4, 'INGLESIDE':5, 
                'TENDERLOIN':6, 'TARAVAL':7, 'PARK':8, 'RICHMOND':9}

train['PdDistrict'].replace(pd_districts, inplace=True)
test['PdDistrict'].replace(pd_districts, inplace=True)

In [97]:
data = [train, test]

for dataset in data:
    year_le = LabelEncoder()
    year_le.fit(dataset['Years'].unique())
    print(list(year_le.classes_))

    dataset['Years']=year_le.transform(dataset['Years'])

[np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015)]
[np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015)]

In [98]:
train['Years'].unique()

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## DayOfWeek
- we are going to use sklearn's LabelEncoder to encode the categorical data to numeric
- Day of week is considered a categorical and nominal variable

In [99]:
data = [train, test]

for dataset in data:
    dow_le = LabelEncoder()
    dow_le.fit(dataset['DayOfWeek'].unique())
    print(list(dow_le.classes_))
    dataset['DayOfWeek']=dow_le.transform(dataset['DayOfWeek'])

['Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']
['Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']

In [100]:
train['DayOfWeek'].unique()

array([6, 5, 1, 3, 2, 0, 4])

In [101]:
# So we know the mapping (important)
dict(zip(dow_le.classes_, dow_le.transform(dow_le.classes_)))

{'Friday': np.int64(0),
 'Monday': np.int64(1),
 'Saturday': np.int64(2),
 'Sunday': np.int64(3),
 'Thursday': np.int64(4),
 'Tuesday': np.int64(5),
 'Wednesday': np.int64(6)}

## Street Type
- we are going to use sklearn's LabelEncoder to encode the categorical data to numeric

In [102]:
data = [train, test]

for dataset in data:
    st_le = LabelEncoder()
    st_le.fit(dataset['StreetType'].unique())
    print(list(st_le.classes_))
    dataset['StreetType']=st_le.transform(dataset['StreetType'])

['AL', 'AV', 'BL', 'CR', 'CT', 'DR', 'EL CAMINO DEL MAR', 'HY', 'I-80', 'INT', 'LN', 'OTHER', 'PL', 'PZ', 'RD', 'RW', 'ST', 'TR', 'WAY', 'WK', 'WY']
['AL', 'AV', 'BL', 'CR', 'CT', 'DR', 'EL CAMINO DEL MAR', 'HY', 'I-80', 'INT', 'LN', 'OTHER', 'PL', 'PZ', 'RD', 'RW', 'ST', 'TR', 'WAY', 'WK', 'WY']